services:
  app:
    command: bundle exec rspec
    build:
      context: .
    user: ${CMPS_UID_GID}
    volumes:
      - '.:/app'
      - 'bundle:/bundle'
      - '~/.gitconfig:/home/nobody/.gitconfig'
      - '~/.gnupg:/home/nobody/.gnupg'
      - '~/.gem:/home/nobody/.gem'
      - '~/.ssh:/home/nobody/.ssh'
    environment:
      RAILS_ENV: development
    ports:
      - 3000:3000

volumes:
  bundle: